### ISSUE TITLE
query about the code

### ISSUE THREAD

**Issue by oneway3124** [pptacher/probabilistic_robotics#1]
Thanks for your sharing. I want to known that whether there are some python code resource about probabilitistic robotics especially in the localization. I will appreciate it if you can tell any message about this topics.

Thanks a lot!
Best Regards,
Wireless Sensor Networks, School of Computer Science, Sichuan University.

Wang Wei(王伟)，  |mobile: +86-159-0810-6107 | email: 190025935@qq.com，2017323040017@stu.scu.edu.cn |website: https://oneway3124.github.io

**Comment by pierrepault** [comment]
Hello,
I do not have particular info to share about this sorry.
best regards
