### ISSUE TITLE
fastslam nodejs/c++ app is not working

### ISSUE THREAD

**Issue by iamnambiar** [pptacher/probabilistic_robotics#10]
When I clicked the link [fastslam nodejs/c++ app](http://35.242.140.13:8080), it is not working.

**Comment by pierrepault** [comment]
Yes indeed unfortunately I do not have google cloud credits anymore so for now the app is not online.

**Comment by iamnambiar** [comment]
> 
> 
> Yes indeed unfortunately I do not have google cloud credits anymore so for now the app is not online.

Ok.
