### ISSUE TITLE
Discussion on solution for problem 2.1 in chapter 6

### ISSUE THREAD

**Issue by RichardTseng2000** [pptacher/probabilistic_robotics#3]
Dear @pptacher 
Thank you for your solutions which help me a lot. However I still have some concern about the solution for problem 2.1 in chapter 6.
As we know, the idea coordinates of the mark image in the camera plan is shown as vector <a href="https://www.codecogs.com/eqnedit.php?latex=\begin{bmatrix}&space;x_{i}&space;\\&space;y_{i}&space;\\&space;\theta&space;_{i}&space;\end{bmatrix}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\begin{bmatrix}&space;x_{i}&space;\\&space;y_{i}&space;\\&space;\theta&space;_{i}&space;\end{bmatrix}" title="\begin{bmatrix} x_{i} \\ y_{i} \\ \theta _{i} \end{bmatrix}" /></a>, while the real coordinates can be shown as vector <a href="https://www.codecogs.com/eqnedit.php?latex=\begin{bmatrix}&space;\widehat{x_{i}}&space;\\&space;\widehat{y_{i}}&space;\\&space;\widehat{\theta&space;_{i}}&space;\end{bmatrix}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\begin{bmatrix}&space;\widehat{x_{i}}&space;\\&space;\widehat{y_{i}}&space;\\&space;\widehat{\theta&space;_{i}}&space;\end{bmatrix}" title="\begin{bmatrix} \widehat{x_{i}} \\ \widehat{y_{i}} \\ \widehat{\theta _{i}} \end{bmatrix}" /></a>. Since the noise in measurement <a href="https://www.codecogs.com/eqnedit.php?latex=\xi\sim&space;N([0\,&space;0\,&space;0],\Sigma&space;)" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\xi\sim&space;N([0\,&space;0\,&space;0],\Sigma&space;)" title="\xi\sim N([0\, 0\, 0],\Sigma )" /></a>, then 
<a href="https://www.codecogs.com/eqnedit.php?latex=\begin{bmatrix}&space;\widehat{x_{i}}&space;\\&space;\widehat{y_{i}}&space;\\&space;\widehat{\theta&space;_{i}}&space;\end{bmatrix}=&space;\begin{bmatrix}&space;x_{i}&space;\\&space;y_{i}&space;\\&space;\theta&space;_{i}&space;\end{bmatrix}&plus;\xi" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\begin{bmatrix}&space;\widehat{x_{i}}&space;\\&space;\widehat{y_{i}}&space;\\&space;\widehat{\theta&space;_{i}}&space;\end{bmatrix}=&space;\begin{bmatrix}&space;x_{i}&space;\\&space;y_{i}&space;\\&space;\theta&space;_{i}&space;\end{bmatrix}&plus;\xi" title="\begin{bmatrix} \widehat{x_{i}} \\ \widehat{y_{i}} \\ \widehat{\theta _{i}} \end{bmatrix}= \begin{bmatrix} x_{i} \\ y_{i} \\ \theta _{i} \end{bmatrix}+\xi" /></a>

So, according to the solution of problem 1.1, we have
<a href="https://www.codecogs.com/eqnedit.php?latex=\begin{bmatrix}&space;x_{m}&space;\\&space;y_{m}&space;\\&space;\theta&space;_{m}&space;\end{bmatrix}&space;=&space;\begin{bmatrix}&space;cos\theta\;&space;-sin\theta&space;\;\;0\\&space;sin\theta\;cos\theta\;\;0&space;\\&space;0\;&space;\;&space;\;&space;\;&space;\;&space;\;&space;\;0\;&space;\;&space;\;&space;\;&space;\;&space;\;&space;1&space;\end{bmatrix}\begin{bmatrix}&space;\frac{h}{f}\;&space;0&space;\;0\\&space;0\;\frac{h}{f}\;&space;0&space;\\&space;0&space;\;\;0\;\;1&space;\end{bmatrix}(&space;\begin{bmatrix}&space;\widehat{x_{i}}&space;\\&space;\widehat{y_{i}}&space;\\&space;\widehat{{\theta&space;_{i}}}&space;\end{bmatrix})&space;&plus;\begin{bmatrix}&space;x_{r}&space;\\&space;y_{r}&space;\\&space;\theta&space;_{r}&space;\end{bmatrix}\\=&space;\begin{bmatrix}&space;cos\theta\;&space;-sin\theta&space;\;\;0\\&space;sin\theta\;cos\theta\;\;0&space;\\&space;0\;&space;\;&space;\;&space;\;&space;\;&space;\;&space;\;0\;&space;\;&space;\;&space;\;&space;\;&space;\;&space;1&space;\end{bmatrix}\begin{bmatrix}&space;\frac{h}{f}\;&space;0&space;\;0\\&space;0\;\frac{h}{f}\;&space;0&space;\\&space;0&space;\;\;0\;\;1&space;\end{bmatrix}(&space;\begin{bmatrix}&space;{x_{i}}&space;\\&space;{y_{i}}&space;\\&space;{\theta&space;_{i}}&space;\end{bmatrix}&plus;\xi)&space;&plus;\begin{bmatrix}&space;x_{r}&space;\\&space;y_{r}&space;\\&space;\theta&space;_{r}&space;\end{bmatrix}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\begin{bmatrix}&space;x_{m}&space;\\&space;y_{m}&space;\\&space;\theta&space;_{m}&space;\end{bmatrix}&space;=&space;\begin{bmatrix}&space;cos\theta\;&space;-sin\theta&space;\;\;0\\&space;sin\theta\;cos\theta\;\;0&space;\\&space;0\;&space;\;&space;\;&space;\;&space;\;&space;\;&space;\;0\;&space;\;&space;\;&space;\;&space;\;&space;\;&space;1&space;\end{bmatrix}\begin{bmatrix}&space;\frac{h}{f}\;&space;0&space;\;0\\&space;0\;\frac{h}{f}\;&space;0&space;\\&space;0&space;\;\;0\;\;1&space;\end{bmatrix}(&space;\begin{bmatrix}&space;\widehat{x_{i}}&space;\\&space;\widehat{y_{i}}&space;\\&space;\widehat{{\theta&space;_{i}}}&space;\end{bmatrix})&space;&plus;\begin{bmatrix}&space;x_{r}&space;\\&space;y_{r}&space;\\&space;\theta&space;_{r}&space;\end{bmatrix}\\=&space;\begin{bmatrix}&space;cos\theta\;&space;-sin\theta&space;\;\;0\\&space;sin\theta\;cos\theta\;\;0&space;\\&space;0\;&space;\;&space;\;&space;\;&space;\;&space;\;&space;\;0\;&space;\;&space;\;&space;\;&space;\;&space;\;&space;1&space;\end{bmatrix}\begin{bmatrix}&space;\frac{h}{f}\;&space;0&space;\;0\\&space;0\;\frac{h}{f}\;&space;0&space;\\&space;0&space;\;\;0\;\;1&space;\end{bmatrix}(&space;\begin{bmatrix}&space;{x_{i}}&space;\\&space;{y_{i}}&space;\\&space;{\theta&space;_{i}}&space;\end{bmatrix}&plus;\xi)&space;&plus;\begin{bmatrix}&space;x_{r}&space;\\&space;y_{r}&space;\\&space;\theta&space;_{r}&space;\end{bmatrix}" title="\begin{bmatrix} x_{m} \\ y_{m} \\ \theta _{m} \end{bmatrix} = \begin{bmatrix} cos\theta\; -sin\theta \;\;0\\ sin\theta\;cos\theta\;\;0 \\ 0\; \; \; \; \; \; \;0\; \; \; \; \; \; 1 \end{bmatrix}\begin{bmatrix} \frac{h}{f}\; 0 \;0\\ 0\;\frac{h}{f}\; 0 \\ 0 \;\;0\;\;1 \end{bmatrix}( \begin{bmatrix} \widehat{x_{i}} \\ \widehat{y_{i}} \\ \widehat{{\theta _{i}}} \end{bmatrix}) +\begin{bmatrix} x_{r} \\ y_{r} \\ \theta _{r} \end{bmatrix}\\= \begin{bmatrix} cos\theta\; -sin\theta \;\;0\\ sin\theta\;cos\theta\;\;0 \\ 0\; \; \; \; \; \; \;0\; \; \; \; \; \; 1 \end{bmatrix}\begin{bmatrix} \frac{h}{f}\; 0 \;0\\ 0\;\frac{h}{f}\; 0 \\ 0 \;\;0\;\;1 \end{bmatrix}( \begin{bmatrix} {x_{i}} \\ {y_{i}} \\ {\theta _{i}} \end{bmatrix}+\xi) +\begin{bmatrix} x_{r} \\ y_{r} \\ \theta _{r} \end{bmatrix}" /></a>
Also it means that
<a href="https://www.codecogs.com/eqnedit.php?latex=\begin{bmatrix}&space;x_{m}&space;\\&space;y_{m}&space;\\&space;\theta&space;_{m}&space;\end{bmatrix}&space;=&space;\begin{bmatrix}&space;cos\theta\;&space;-sin\theta&space;\;\;0\\&space;sin\theta\;cos\theta\;\;0&space;\\&space;0\;&space;\;&space;\;&space;\;&space;\;&space;\;&space;\;0\;&space;\;&space;\;&space;\;&space;\;&space;\;&space;1&space;\end{bmatrix}\begin{bmatrix}&space;\frac{h}{f}\;&space;0&space;\;0\\&space;0\;\frac{h}{f}\;&space;0&space;\\&space;0&space;\;\;0\;\;1&space;\end{bmatrix}\xi&space;&plus;&space;\begin{bmatrix}&space;cos\theta\;&space;-sin\theta&space;\;\;0\\&space;sin\theta\;cos\theta\;\;0&space;\\&space;0\;&space;\;&space;\;&space;\;&space;\;&space;\;&space;\;0\;&space;\;&space;\;&space;\;&space;\;&space;\;&space;1&space;\end{bmatrix}\begin{bmatrix}&space;\frac{h}{f}\;&space;0&space;\;0\\&space;0\;\frac{h}{f}\;&space;0&space;\\&space;0&space;\;\;0\;\;1&space;\end{bmatrix}&space;\begin{bmatrix}&space;{x_{i}}&space;\\&space;{y_{i}}&space;\\&space;{\theta&space;_{i}}&space;\end{bmatrix}&plus;\begin{bmatrix}&space;x_{r}&space;\\&space;y_{r}&space;\\&space;\theta&space;_{r}&space;\end{bmatrix}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\begin{bmatrix}&space;x_{m}&space;\\&space;y_{m}&space;\\&space;\theta&space;_{m}&space;\end{bmatrix}&space;=&space;\begin{bmatrix}&space;cos\theta\;&space;-sin\theta&space;\;\;0\\&space;sin\theta\;cos\theta\;\;0&space;\\&space;0\;&space;\;&space;\;&space;\;&space;\;&space;\;&space;\;0\;&space;\;&space;\;&space;\;&space;\;&space;\;&space;1&space;\end{bmatrix}\begin{bmatrix}&space;\frac{h}{f}\;&space;0&space;\;0\\&space;0\;\frac{h}{f}\;&space;0&space;\\&space;0&space;\;\;0\;\;1&space;\end{bmatrix}\xi&space;&plus;&space;\begin{bmatrix}&space;cos\theta\;&space;-sin\theta&space;\;\;0\\&space;sin\theta\;cos\theta\;\;0&space;\\&space;0\;&space;\;&space;\;&space;\;&space;\;&space;\;&space;\;0\;&space;\;&space;\;&space;\;&space;\;&space;\;&space;1&space;\end{bmatrix}\begin{bmatrix}&space;\frac{h}{f}\;&space;0&space;\;0\\&space;0\;\frac{h}{f}\;&space;0&space;\\&space;0&space;\;\;0\;\;1&space;\end{bmatrix}&space;\begin{bmatrix}&space;{x_{i}}&space;\\&space;{y_{i}}&space;\\&space;{\theta&space;_{i}}&space;\end{bmatrix}&plus;\begin{bmatrix}&space;x_{r}&space;\\&space;y_{r}&space;\\&space;\theta&space;_{r}&space;\end{bmatrix}" title="\begin{bmatrix} x_{m} \\ y_{m} \\ \theta _{m} \end{bmatrix} = \begin{bmatrix} cos\theta\; -sin\theta \;\;0\\ sin\theta\;cos\theta\;\;0 \\ 0\; \; \; \; \; \; \;0\; \; \; \; \; \; 1 \end{bmatrix}\begin{bmatrix} \frac{h}{f}\; 0 \;0\\ 0\;\frac{h}{f}\; 0 \\ 0 \;\;0\;\;1 \end{bmatrix}\xi + \begin{bmatrix} cos\theta\; -sin\theta \;\;0\\ sin\theta\;cos\theta\;\;0 \\ 0\; \; \; \; \; \; \;0\; \; \; \; \; \; 1 \end{bmatrix}\begin{bmatrix} \frac{h}{f}\; 0 \;0\\ 0\;\frac{h}{f}\; 0 \\ 0 \;\;0\;\;1 \end{bmatrix} \begin{bmatrix} {x_{i}} \\ {y_{i}} \\ {\theta _{i}} \end{bmatrix}+\begin{bmatrix} x_{r} \\ y_{r} \\ \theta _{r} \end{bmatrix}" /></a>

Considern that in problem 2.1 <a href="https://www.codecogs.com/eqnedit.php?latex=\begin{bmatrix}&space;x_{m}&space;\\&space;y_{m}&space;\\&space;\theta&space;_{m}&space;\end{bmatrix}\sim&space;N(\mu&space;_{m},\Sigma&space;_{m})" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\begin{bmatrix}&space;x_{m}&space;\\&space;y_{m}&space;\\&space;\theta&space;_{m}&space;\end{bmatrix}\sim&space;N(\mu&space;_{m},\Sigma&space;_{m})" title="\begin{bmatrix} x_{m} \\ y_{m} \\ \theta _{m} \end{bmatrix}\sim N(\mu _{m},\Sigma _{m})" /></a>, then
<a href="https://www.codecogs.com/eqnedit.php?latex=\Sigma&space;_{m}=&space;\begin{bmatrix}&space;cos\theta\;&space;-sin\theta&space;\;\;0\\&space;sin\theta\;cos\theta\;\;0&space;\\&space;0\;&space;\;&space;\;&space;\;&space;\;&space;\;&space;\;0\;&space;\;&space;\;&space;\;&space;\;&space;\;&space;1&space;\end{bmatrix}\begin{bmatrix}&space;\frac{h}{f}\;&space;0&space;\;0\\&space;0\;\frac{h}{f}\;&space;0&space;\\&space;0&space;\;\;0\;\;1&space;\end{bmatrix}\Sigma(&space;\begin{bmatrix}&space;cos\theta\;&space;-sin\theta&space;\;\;0\\&space;sin\theta\;cos\theta\;\;0&space;\\&space;0\;&space;\;&space;\;&space;\;&space;\;&space;\;&space;\;0\;&space;\;&space;\;&space;\;&space;\;&space;\;&space;1&space;\end{bmatrix}\begin{bmatrix}&space;\frac{h}{f}\;&space;0&space;\;0\\&space;0\;\frac{h}{f}\;&space;0&space;\\&space;0&space;\;\;0\;\;1&space;\end{bmatrix})^{T}&space;\\=&space;\begin{bmatrix}&space;cos\theta\;&space;-sin\theta&space;\;\;0\\&space;sin\theta\;cos\theta\;\;0&space;\\&space;0\;&space;\;&space;\;&space;\;&space;\;&space;\;&space;\;0\;&space;\;&space;\;&space;\;&space;\;&space;\;&space;1&space;\end{bmatrix}\begin{bmatrix}&space;\frac{h}{f}\;&space;0&space;\;0\\&space;0\;\frac{h}{f}\;&space;0&space;\\&space;0&space;\;\;0\;\;1&space;\end{bmatrix}\begin{bmatrix}&space;\sigma^{2}\;0\;0\\&space;0\;\sigma^{2}\;0\\&space;0\;\;0\;\;0\\&space;\end{bmatrix}(&space;\begin{bmatrix}&space;cos\theta\;&space;-sin\theta&space;\;\;0\\&space;sin\theta\;cos\theta\;\;0&space;\\&space;0\;&space;\;&space;\;&space;\;&space;\;&space;\;&space;\;0\;&space;\;&space;\;&space;\;&space;\;&space;\;&space;1&space;\end{bmatrix}\begin{bmatrix}&space;\frac{h}{f}\;&space;0&space;\;0\\&space;0\;\frac{h}{f}\;&space;0&space;\\&space;0&space;\;\;0\;\;1&space;\end{bmatrix})^{T}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\Sigma&space;_{m}=&space;\begin{bmatrix}&space;cos\theta\;&space;-sin\theta&space;\;\;0\\&space;sin\theta\;cos\theta\;\;0&space;\\&space;0\;&space;\;&space;\;&space;\;&space;\;&space;\;&space;\;0\;&space;\;&space;\;&space;\;&space;\;&space;\;&space;1&space;\end{bmatrix}\begin{bmatrix}&space;\frac{h}{f}\;&space;0&space;\;0\\&space;0\;\frac{h}{f}\;&space;0&space;\\&space;0&space;\;\;0\;\;1&space;\end{bmatrix}\Sigma(&space;\begin{bmatrix}&space;cos\theta\;&space;-sin\theta&space;\;\;0\\&space;sin\theta\;cos\theta\;\;0&space;\\&space;0\;&space;\;&space;\;&space;\;&space;\;&space;\;&space;\;0\;&space;\;&space;\;&space;\;&space;\;&space;\;&space;1&space;\end{bmatrix}\begin{bmatrix}&space;\frac{h}{f}\;&space;0&space;\;0\\&space;0\;\frac{h}{f}\;&space;0&space;\\&space;0&space;\;\;0\;\;1&space;\end{bmatrix})^{T}&space;\\=&space;\begin{bmatrix}&space;cos\theta\;&space;-sin\theta&space;\;\;0\\&space;sin\theta\;cos\theta\;\;0&space;\\&space;0\;&space;\;&space;\;&space;\;&space;\;&space;\;&space;\;0\;&space;\;&space;\;&space;\;&space;\;&space;\;&space;1&space;\end{bmatrix}\begin{bmatrix}&space;\frac{h}{f}\;&space;0&space;\;0\\&space;0\;\frac{h}{f}\;&space;0&space;\\&space;0&space;\;\;0\;\;1&space;\end{bmatrix}\begin{bmatrix}&space;\sigma^{2}\;0\;0\\&space;0\;\sigma^{2}\;0\\&space;0\;\;0\;\;0\\&space;\end{bmatrix}(&space;\begin{bmatrix}&space;cos\theta\;&space;-sin\theta&space;\;\;0\\&space;sin\theta\;cos\theta\;\;0&space;\\&space;0\;&space;\;&space;\;&space;\;&space;\;&space;\;&space;\;0\;&space;\;&space;\;&space;\;&space;\;&space;\;&space;1&space;\end{bmatrix}\begin{bmatrix}&space;\frac{h}{f}\;&space;0&space;\;0\\&space;0\;\frac{h}{f}\;&space;0&space;\\&space;0&space;\;\;0\;\;1&space;\end{bmatrix})^{T}" title="\Sigma _{m}= \begin{bmatrix} cos\theta\; -sin\theta \;\;0\\ sin\theta\;cos\theta\;\;0 \\ 0\; \; \; \; \; \; \;0\; \; \; \; \; \; 1 \end{bmatrix}\begin{bmatrix} \frac{h}{f}\; 0 \;0\\ 0\;\frac{h}{f}\; 0 \\ 0 \;\;0\;\;1 \end{bmatrix}\Sigma( \begin{bmatrix} cos\theta\; -sin\theta \;\;0\\ sin\theta\;cos\theta\;\;0 \\ 0\; \; \; \; \; \; \;0\; \; \; \; \; \; 1 \end{bmatrix}\begin{bmatrix} \frac{h}{f}\; 0 \;0\\ 0\;\frac{h}{f}\; 0 \\ 0 \;\;0\;\;1 \end{bmatrix})^{T} \\= \begin{bmatrix} cos\theta\; -sin\theta \;\;0\\ sin\theta\;cos\theta\;\;0 \\ 0\; \; \; \; \; \; \;0\; \; \; \; \; \; 1 \end{bmatrix}\begin{bmatrix} \frac{h}{f}\; 0 \;0\\ 0\;\frac{h}{f}\; 0 \\ 0 \;\;0\;\;1 \end{bmatrix}\begin{bmatrix} \sigma^{2}\;0\;0\\ 0\;\sigma^{2}\;0\\ 0\;\;0\;\;0\\ \end{bmatrix}( \begin{bmatrix} cos\theta\; -sin\theta \;\;0\\ sin\theta\;cos\theta\;\;0 \\ 0\; \; \; \; \; \; \;0\; \; \; \; \; \; 1 \end{bmatrix}\begin{bmatrix} \frac{h}{f}\; 0 \;0\\ 0\;\frac{h}{f}\; 0 \\ 0 \;\;0\;\;1 \end{bmatrix})^{T}" /></a>

Also it means that 

<a href="https://www.codecogs.com/eqnedit.php?latex=\Sigma&space;_{m}=\begin{bmatrix}&space;(\frac{h}{f}\sigma)^{2}\;0\;0\\&space;0\;\;(\frac{h}{f}\sigma)^{2}\;0\\&space;0\;\;0\;\;0\\&space;\end{bmatrix}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\Sigma&space;_{m}=\begin{bmatrix}&space;(\frac{h}{f}\sigma)^{2}\;0\;0\\&space;0\;\;(\frac{h}{f}\sigma)^{2}\;0\\&space;0\;\;0\;\;0\\&space;\end{bmatrix}" title="\Sigma _{m}=\begin{bmatrix} (\frac{h}{f}\sigma)^{2}\;0\;0\\ 0\;\;(\frac{h}{f}\sigma)^{2}\;0\\ 0\;\;0\;\;0\\ \end{bmatrix}" /></a>

rathern than <a href="https://www.codecogs.com/eqnedit.php?latex=\begin{bmatrix}&space;\sigma^{2}\;0\;0\\&space;0\;\sigma^{2}\;0\\&space;0\;\;0\;\;0\\&space;\end{bmatrix}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\begin{bmatrix}&space;\sigma^{2}\;0\;0\\&space;0\;\sigma^{2}\;0\\&space;0\;\;0\;\;0\\&space;\end{bmatrix}" title="\begin{bmatrix} \sigma^{2}\;0\;0\\ 0\;\sigma^{2}\;0\\ 0\;\;0\;\;0\\ \end{bmatrix}" /></a> as shown in the solution of problem 2.1
That is all and it is very appreciated to get your response  in the future.

**Comment by pierrepault** [comment]
dear @RichardTseng2000 

indeed, a parenthesis was in a wrong place. I corrected exercice 2.
Thank you for the careful reading.

**Comment by RichardTseng2000** [comment]
Dear @pptacher 
Thank you for your response and goodness. Indeed, compared to your contribution to the solutions of those exercises in this book, what I did is too tiny to be mentioned ^v^
