### ISSUE TITLE
problem 1 on chapter 2

### ISSUE THREAD

**Issue by Zacharyzqc** [pptacher/probabilistic_robotics#4]
![image](https://user-images.githubusercontent.com/41284846/74343761-86f15080-4de6-11ea-85df-217a7cf7a584.png)

I wanna know that why  
P(X0=1) = p(1-p) 
rather than
P(X0=1) = 1-p

**Comment by Zacharyzqc** [comment]
P(Xn = 1 |z1:n) = ηP(zn| Xt = 1; z1:n−1) × P(Xn = 1 | z1:n−1)
= ηP(zn | Xt = 1; z1:n−1) × P(Xn−1 = 1| z1:n−1)
= η ×(1/ 3)× P(Xn−1 = 1 | z1:n−1)
= η ×(1/3)^n × P(X0 = 1) (recurrence)
= η ×(1/3)^n× p(1 − p)

**Comment by pierrepault** [comment]
I corrected it. Thank you for pointing it out.
