### ISSUE TITLE
Ch.2 Exercise 3.1

### ISSUE THREAD

**Issue by bugerry87** [pptacher/probabilistic_robotics#6]
Have you mixed up the transition-matrix for day 3-4? Although, day 5 is correct anyway because day 4 eliminates the error.

E.g.: My approx results for P(X_3=i | z_{2:3}) = (0.599, 0.282, 0.0)

Thx for your great work!

**Comment by pierrepault** [comment]
@bugerry87  Thanks for your support. Indeed there is a mistake but do we agree on this one (day 2) ?

P(X₂=i | z₂) = (0.70,0.30,0.00)

**Comment by pierrepault** [comment]
I corrected some calculations in ex3. Do not hesitate to let me know if this does not agree with your results (in any case the numbers you provided do not sum up to 1 so they cannot be correct).

**Comment by bugerry87** [comment]
Oh sorry for the late reply.
Yes, I confirm with your results now.
In my case I might have made some typo within the normalization.

So thx, I will also correct my version and put yours to my references.

https://github.com/bugerry87/sdc/blob/master/RecursiveStateEstimation_GeraldBaulig.ipynb
